name : Security Tools Integration - Sample
on:

  workflow_dispatch:

jobs:

  blackduck_scan:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses : actions/checkout@v3

        
      - name: Black Duck SCA Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0

        env:
          DETECT_PROJECT_NAME: ${{github.event.repository.name}} #Repository name needs to be set as the project name
          DETECT_PROJECT_VERSION_NAME: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} #branch name needs to be set as the version name
          DETECT_TOOLS: "DETECTOR"
          DETECT_DETECTOR_SEARCH_DEPTH: 7 #The folder depth untill which the scan needs to be done
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}  #Needs to be set in the 'secrets and variable' section of the github actions settings
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }} #To be extracted from BlackDuck (Profile -> Access Tokens -> Create Access Token -> Enter Name -> Scope(Read and Write Access) -> Create) and needs to be set in the 'secrets nad variable' section of the github actions settings.
          blackduck_scan_full: true #Full or Rapid scan
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL,MAJOR'

  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v3

      - name : RUN bash script
        run : echo Build Complete
