name : Security Tools Integration - Sample
on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  blackduck_scan:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses : actions/checkout@v3
        
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Black Duck SCA Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0

        env:
          DETECT_PROJECT_NAME: ${{github.event.repository.name}} #Repository name needs to be set as the project name
          DETECT_PROJECT_VERSION_NAME: ${{steps.extract_branch.outputs.branch}}
          DETECT_TOOLS: "DETECTOR,SIGNATURE_SCAN,BINARY_SCAN,THREAT_INTEL,COMPONENT_LOCATION_ANALYSIS"
          DETECT_DETECTOR_SEARCH_DEPTH: 7 #The folder depth untill which the scan needs to be done
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}  #Needs to be set in the 'secrets and variable' section of the github actions settings
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }} #To be extracted from BlackDuck (Profile -> Access Tokens -> Create Access Token -> Enter Name -> Scope(Read and Write Access) -> Create) and needs to be set in the 'secrets nad variable' section of the github actions settings.
          blackducksca_scan_full: true #Full or Rapid scan
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
  coverity_scan:
    defaults: 
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Coverity Full Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        env:
          coverity-checker-options: --all-security
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ vars.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-${{ steps.extract_branch.outputs.branch }}
          coverity_local: true  

  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v3

      - name : RUN bash script
        run : echo Build Complete
