name : Security Tools Integration - Sample
on:

  workflow_dispatch:

jobs:

  build:
    defaults:
      run:
        shell: bash
        working-directory: ./src/integration
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v3

      - name : RUN bash script
        run : echo Build Complete

  blackduck_scan:
    defaults:
      run:
        shell: bash
        working-directory: ./src/integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses : actions/checkout@v3

        
      - name: Black Duck SCA Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0

        env:
          DETECT_PROJECT_NAME: product-security-test-project
          DETECT_PROJECT_VERSION_NAME: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          DETECT_TOOLS: "DETECTOR"
          DETECT_DETECTOR_SEARCH_DEPTH: 7
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_full: true
          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL,MAJOR'
